//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Spaicial_API.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class spaicial_dbEntities : DbContext
    {
        public spaicial_dbEntities()
            : base("name=spaicial_dbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ApiKey> ApiKey { get; set; }
        public virtual DbSet<Bias> Bias { get; set; }
        public virtual DbSet<DataSubject> DataSubject { get; set; }
        public virtual DbSet<Feature> Feature { get; set; }
        public virtual DbSet<ScoutData> ScoutData { get; set; }
        public virtual DbSet<ScoutDataPart> ScoutDataPart { get; set; }
        public virtual DbSet<StationData> StationData { get; set; }
        public virtual DbSet<StationDataPart> StationDataPart { get; set; }
        public virtual DbSet<Zone> Zone { get; set; }
    }
}
