//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Spaicial_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StationDataPart
    {
        public int stationDataId { get; set; }
        public int dataSubjectId { get; set; }
        public double dataValue { get; set; }
    
        public virtual DataSubject DataSubject { get; set; }
        public virtual StationData StationData { get; set; }
    }
}
