//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Spaicial_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StationData
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public StationData()
        {
            this.StationDataPart = new HashSet<StationDataPart>();
        }
    
        public int stationDataId { get; set; }
        public int apiKeyId { get; set; }
        public int zoneId { get; set; }
        public System.DateTime dateTimeCollected { get; set; }
    
        public virtual ApiKey ApiKey { get; set; }
        public virtual Zone Zone { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StationDataPart> StationDataPart { get; set; }
    }
}
